### ISSUE TITLE
About refusal prediction when evaluate coco instance segmentation

### ISSUE THREAD

**Issue by xemcerk** [zamling/PSALM#19]
Hi, thanks for your great work and I'm trying to reproduce the result on coco instance segmentation, but keep getting this error

`Traceback (most recent call last):
  File "/home2020/home/icube/shili/workspace/PSALM/psalm/eval/instance_segmentation.py", line 168, in <module>
    evaluation()
  File "/home2020/home/icube/shili/workspace/PSALM/psalm/eval/instance_segmentation.py", line 141, in evaluation
    for idx, inputs in tqdm(enumerate(eval_dataloader), total=len(eval_dataloader)):
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home2020/home/icube/shili/.conda/envs/psalm/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home2020/home/icube/shili/workspace/PSALM/psalm/train/train_datasets.py", line 455, in __getitem__
    data_dict = processor.preprocess(data_dict, mask_format=self.mask_format)
  File "/home2020/home/icube/shili/workspace/PSALM/psalm/model/datasets_mapper/coco_instance_mapper.py", line 233, in preprocess
    if 'point_visual_prompt_mask' in annos[0]:
IndexError: list index out of range`

It's caused by those images without segmentation masks, seems the common practice here is to include these images while evaluating, and if the model doesn't refuse to give a prediction it will be counted as false positive when calculating metrics. Could you please share that how you deal with that? Thanks a lot in advance!

**Comment by zamling** [comment]
Hi @xemcerk 
Sorry for the delayed response
1. download corresponding files from [here](https://github.com/zamling/PSALM/blob/main/docs/DATASET.md#download-converted-dataset-files), including  `instruction_dataset_coco_format.json` and`instruction_dataset_coco_format.json.lock` files which contain the GT for COCO instance
2. put these two file in your COCO instance `output_dir`, such as `psalm/output/instance_segmentation`
3. run evaluation script again

These steps can build a converted files for evaluation, rather than building these in COCO evaluator.
Hoping these are work for you

**Comment by xemcerk** [comment]
> Hi @xemcerk Sorry for the delayed response
> 
> 1. download corresponding files from [here](https://github.com/zamling/PSALM/blob/main/docs/DATASET.md#download-converted-dataset-files), including  `instruction_dataset_coco_format.json` and`instruction_dataset_coco_format.json.lock` files which contain the GT for COCO instance
> 2. put these two file in your COCO instance `output_dir`, such as `psalm/output/instance_segmentation`
> 3. run evaluation script again
> 
> These steps can build a converted files for evaluation, rather than building these in COCO evaluator. Hoping these are work for you

Thank you very much for providing help! It seems like I still have to filter out background images in the datasets/coco/instance_val_psalm.json to make it work, otherwise it will be the same error even after I follow mentioned steps to bypass building converted files in coco evaluator.

**Comment by zamling** [comment]
Yeah, you are right
May be I need to update COCO instance dataloader pipline to make it handle image without masks
